"""Init SQLite tables

Revision ID: 4aad4cc90519
Revises: 
Create Date: 2026-07-12 22:22:35.840869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aad4cc90519'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('channels',
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('custom_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=False),
    sa.Column('video_count', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channels_country_code'), 'channels', ['country_code'], unique=False)
    op.create_index(op.f('ix_channels_title'), 'channels', ['title'], unique=False)
    op.create_table('channel_rank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'period', 'country_code', 'rank_date', name='uq_channel_rank_unique')
    )
    op.create_index(op.f('ix_channel_rank_channel_id'), 'channel_rank', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_rank_country_code'), 'channel_rank', ['country_code'], unique=False)
    op.create_index(op.f('ix_channel_rank_period'), 'channel_rank', ['period'], unique=False)
    op.create_index(op.f('ix_channel_rank_rank_date'), 'channel_rank', ['rank_date'], unique=False)
    op.create_table('videos',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('subscriber', sa.BigInteger(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('isShort', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_country_code'), 'videos', ['country_code'], unique=False)
    op.create_index(op.f('ix_videos_isShort'), 'videos', ['isShort'], unique=False)
    op.create_index(op.f('ix_videos_publish_time'), 'videos', ['publish_time'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('why_popular', sa.Text(), nullable=False),
    sa.Column('key_success_factors', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('similar_contents', sa.Text(), nullable=False),
    sa.Column('prediction_24h', sa.Text(), nullable=False),
    sa.Column('improvement_ideas', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_ai_analysis_video_id'), 'ai_analysis', ['video_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_video_id'), 'alerts', ['video_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=True)
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_user_channel_favorite'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_favorite')
    )
    op.create_index(op.f('ix_favorites_channel_id'), 'favorites', ['channel_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_video_id'), 'favorites', ['video_id'], unique=False)
    op.create_table('ranking_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_history_country_code'), 'ranking_history', ['country_code'], unique=False)
    op.create_index(op.f('ix_ranking_history_recorded_at'), 'ranking_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_ranking_history_video_id'), 'ranking_history', ['video_id'], unique=False)
    op.create_table('thumbnail_analysis',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=False),
    sa.Column('dominant_colors', sa.JSON(), nullable=True),
    sa.Column('object_tags', sa.JSON(), nullable=True),
    sa.Column('aesthetic_score', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_thumbnail_analysis_video_id'), 'thumbnail_analysis', ['video_id'], unique=False)
    op.create_table('title_analysis',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=False),
    sa.Column('clickbait_score', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_title_analysis_video_id'), 'title_analysis', ['video_id'], unique=False)
    op.create_table('trend_prediction',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('predicted_views_24h', sa.BigInteger(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_trend_prediction_video_id'), 'trend_prediction', ['video_id'], unique=False)
    op.create_table('video_rank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=False),
    sa.Column('is_shorts', sa.Boolean(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'period', 'country_code', 'rank_date', name='uq_video_rank_unique')
    )
    op.create_index(op.f('ix_video_rank_country_code'), 'video_rank', ['country_code'], unique=False)
    op.create_index(op.f('ix_video_rank_is_shorts'), 'video_rank', ['is_shorts'], unique=False)
    op.create_index(op.f('ix_video_rank_period'), 'video_rank', ['period'], unique=False)
    op.create_index(op.f('ix_video_rank_rank_date'), 'video_rank', ['rank_date'], unique=False)
    op.create_index(op.f('ix_video_rank_video_id'), 'video_rank', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_rank_video_id'), table_name='video_rank')
    op.drop_index(op.f('ix_video_rank_rank_date'), table_name='video_rank')
    op.drop_index(op.f('ix_video_rank_period'), table_name='video_rank')
    op.drop_index(op.f('ix_video_rank_is_shorts'), table_name='video_rank')
    op.drop_index(op.f('ix_video_rank_country_code'), table_name='video_rank')
    op.drop_table('video_rank')
    op.drop_index(op.f('ix_trend_prediction_video_id'), table_name='trend_prediction')
    op.drop_table('trend_prediction')
    op.drop_index(op.f('ix_title_analysis_video_id'), table_name='title_analysis')
    op.drop_table('title_analysis')
    op.drop_index(op.f('ix_thumbnail_analysis_video_id'), table_name='thumbnail_analysis')
    op.drop_table('thumbnail_analysis')
    op.drop_index(op.f('ix_ranking_history_video_id'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_recorded_at'), table_name='ranking_history')
    op.drop_index(op.f('ix_ranking_history_country_code'), table_name='ranking_history')
    op.drop_table('ranking_history')
    op.drop_index(op.f('ix_favorites_video_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_channel_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_alerts_video_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_analysis_video_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_publish_time'), table_name='videos')
    op.drop_index(op.f('ix_videos_isShort'), table_name='videos')
    op.drop_index(op.f('ix_videos_country_code'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_channel_rank_rank_date'), table_name='channel_rank')
    op.drop_index(op.f('ix_channel_rank_period'), table_name='channel_rank')
    op.drop_index(op.f('ix_channel_rank_country_code'), table_name='channel_rank')
    op.drop_index(op.f('ix_channel_rank_channel_id'), table_name='channel_rank')
    op.drop_table('channel_rank')
    op.drop_index(op.f('ix_channels_title'), table_name='channels')
    op.drop_index(op.f('ix_channels_country_code'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
