"""add target_age and target_gender columns to videos

Revision ID: a0528a605135
Revises: 4aad4cc90519
Create Date: 2026-08-13 19:11:25.197642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0528a605135'
down_revision: Union[str, None] = '4aad4cc90519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('target_age', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('target_gender', sa.String(), nullable=True))
    op.create_index(op.f('ix_videos_target_age'), 'videos', ['target_age'], unique=False)
    op.create_index(op.f('ix_videos_target_gender'), 'videos', ['target_gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_target_gender'), table_name='videos')
    op.drop_index(op.f('ix_videos_target_age'), table_name='videos')
    op.drop_column('videos', 'target_gender')
    op.drop_column('videos', 'target_age')
    # ### end Alembic commands ###
