from typing import List, Optional
from fastapi import APIRouter, Depends, Query, HTTPException

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update
from sqlalchemy.orm import joinedload
from database.connection import get_db
from models.interaction import Alert
from schemas.alert import AlertResponse

router = APIRouter(prefix="/alerts", tags=["Alerts"])

@router.get("", response_model=List[AlertResponse])
async def read_alerts(
    limit: int = Query(50, ge=1, le=100),
    is_read: Optional[bool] = Query(None, description="Filter by read/unread status"),
    db: AsyncSession = Depends(get_db)
):
    """
    Get system alerts generated by Virality score peaks and hidden gem discoveries.
    """
    query = select(Alert).options(joinedload(Alert.video)).order_by(Alert.created_at.desc()).limit(limit)
    if is_read is not None:
        query = query.where(Alert.is_read == is_read)
    
    result = await db.execute(query)
    alerts = result.scalars().all()
    return alerts

@router.post("/{alert_id}/read", response_model=AlertResponse)
async def mark_alert_as_read(
    alert_id: int,
    db: AsyncSession = Depends(get_db)
):
    """
    Mark a specific alert as read.
    """
    query = select(Alert).where(Alert.alert_id == alert_id).options(joinedload(Alert.video))
    result = await db.execute(query)
    alert = result.scalar_one_or_none()
    
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    alert.is_read = True
    await db.commit()
    await db.refresh(alert)
    return alert
